# -*- coding: utf-8 -*-
"""1- Geração de Mensagem de Erro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZj6WN53d73YJZe1TFHogyt0ChilJ8TN
"""

# Generation of Error Message Containing Sensitive Information

import sqlite3

def get_name(nome):
    try:

        coneccao = sqlite3.connect('users.db')
        cursor = coneccao.cursor()

        cursor.execute(f"SELECT * FROM users WHERE username = '{nome}'")
        user = cursor.fetchone()

        if user:
            return user
        else:
            return "Usuário não encontrado."
    except Exception as e:
        return f"Ocorreu um erro: {str(e)}"
    finally:
        coneccao.close()

print(get_name("admin' OR 1=1 --"))

# Correção

import sqlite3
def get_name(nome):
    try:
        coneccao = sqlite3.connect('users.db')
        cursor = coneccao.cursor()
        cursor.execute("SELECT * FROM users WHERE username = ?", (nome,))
        user = cursor.fetchone()

        if user:
            return user
        else:
            return "Usuário não encontrado."

    except Exception as e:
        log_error(e)
        return "Ocorreu um erro, por favor tente novamente mais tarde."
    finally:
        coneccao.close()

def log_error(error):
    with open("error_log.txt", "a") as log_file:
        log_file.write(str(error) + "\n")

print(get_name("admin' OR 1=1 --"))